name: CMake

on:
  push:
    branches: [ main ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '.github/workflows/**'
      
  pull_request:
    branches: [ main ]
    paths:
      - '**.cpp'
      - '**.hpp'
env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install package
      run: sudo apt-get -y install libcppunit-dev cppcheck clang-tidy-11 libboost-program-options-dev ccache gcovr

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    
    - name: Check 1 -> cppcheck
      run: cmake --build ${{github.workspace}}/build --target cppcheck

    # - name: Check 2 -> clang-tidy
    #   run: clang-tidy-11 src/* -- -I include/ -I build/generated/

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
      
    - name: Coverage
      run: gcovr -r ../ .
