name: Formatting

on:
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Install package
      run: sudo apt-get -y install clang-format-11

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Format
      run: |
        cmake --build ${{github.workspace}}/build --target clang-format

    - name: Commit report
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "Automated formatting" || true
        git push || true
